service:
  name: hakataarchiver

custom:
  defaultStage: dev
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  profiles:
    dev: serverless
    prod: null

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    HAKATASHI_API_KEY: ${env:HAKATASHI_API_KEY}
  profile: ${self:custom.profiles.${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

functions:
  crawlPixiv:
    handler: handler.crawlPixiv
    events:
      - http:
          method: post
          path: crawl-pixiv
    timeout: 300
  postSession:
    handler: handler.postSession
    events:
      - http:
          method: post
          path: post-session
